[project]
name = "09_ax_club"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "whale2200d", email = "whale2200d@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "anthropic>=1.11.0",
    "google-genai>=2.28.0",
    "python-dotenv>=1.2.4",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
